[build]
builder = "DOCKERFILE"
dockerfilePath = "backend/Dockerfile"

[deploy]
startCommand = "uvicorn main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production.variables]
DEBUG = "false"
LOG_LEVEL = "INFO"
BINANCE_TESTNET = "false"  # LIVE TRADING ENABLED

# Production Performance Settings
WORKERS = "4"
MAX_REQUESTS = "1000"
MAX_REQUESTS_JITTER = "50"
TIMEOUT = "30"

# Security Settings
SECURE_HEADERS = "true"
CORS_ALLOWED_ORIGINS = "*"
RATE_LIMIT_ENABLED = "true"
RATE_LIMIT_MAX_REQUESTS = "100"
RATE_LIMIT_WINDOW_SECONDS = "60"

# Trading Safety Switches
TRADING_ENABLED = "true"
LIVE_CAPITAL_ENABLED = "true"
AUTO_TRADING_ENABLED = "false"  # Manual confirmation required initially

# Monitoring
ENABLE_METRICS = "true"
ENABLE_TRACING = "true"
SENTRY_DSN = ""  # Add your Sentry DSN if available